name: flutter_tutorial
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Updated to use SDK version 3.5.0 or higher

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0   # Updated to the latest compatible version para yoga: ^2.3.3+2
  path: ^1.9.0
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.6
  flutter_pdfview: ^1.0.0  #Instalar un paquete para leer PDFs ^2.0.4
  url_launcher: ^6.1.10

  youtube_player_flutter: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/pdf/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-Italic.ttf
        style: italic
      - asset: assets/fonts/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
